/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Telas;

import entities.Cliente;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Bruno
 */
public class Main extends javax.swing.JDialog {

    /**
     * Creates new form Tela
     */
    public Main(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.BLACK);
    }

    NumberFormat formatter = new DecimalFormat("0.00");
    Cliente cli;

    
    public void montaTela(Cliente cli) {
        cSaldoTotal.setText("R$ " + formatter.format(cli.getSaldoDaConta()));
        cSaldoDasRodadas.setText("R$ 00,00");
        cNome.setText(cli.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cSaldoTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        perdi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cSaldoDasRodadas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nova = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cRodadaAtual = new javax.swing.JTextField();
        cNome = new javax.swing.JTextField();
        ganhei = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cCalcPraColocar = new javax.swing.JTextField();
        nova1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jButton5.setText("+ 10");

        jButton6.setText("- 10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interface de Apostas");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apostador:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo Atual Total:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        cSaldoTotal.setEditable(false);
        cSaldoTotal.setBackground(new java.awt.Color(51, 51, 51));
        cSaldoTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cSaldoTotal.setForeground(new java.awt.Color(255, 255, 255));
        cSaldoTotal.setCaretColor(new java.awt.Color(255, 255, 255));
        cSaldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSaldoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(cSaldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 395, 103, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor que vou apostar na rodada: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        perdi.setBackground(new java.awt.Color(0, 0, 0));
        perdi.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        perdi.setForeground(new java.awt.Color(255, 0, 0));
        perdi.setText("Perdi");
        getContentPane().add(perdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 80, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo das Rodadas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        cSaldoDasRodadas.setEditable(false);
        cSaldoDasRodadas.setBackground(new java.awt.Color(51, 51, 51));
        cSaldoDasRodadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cSaldoDasRodadas.setForeground(new java.awt.Color(255, 255, 255));
        cSaldoDasRodadas.setCaretColor(new java.awt.Color(255, 255, 255));
        cSaldoDasRodadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSaldoDasRodadasActionPerformed(evt);
            }
        });
        getContentPane().add(cSaldoDasRodadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 355, 103, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rodada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        nova.setBackground(new java.awt.Color(0, 0, 0));
        nova.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        nova.setForeground(new java.awt.Color(255, 255, 255));
        nova.setText("Sair");
        nova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaActionPerformed(evt);
            }
        });
        getContentPane().add(nova, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 60, 30));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quanto devo colocar na rodada:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cRodadaAtual.setBackground(new java.awt.Color(51, 51, 51));
        cRodadaAtual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cRodadaAtual.setForeground(new java.awt.Color(255, 255, 255));
        cRodadaAtual.setCaretColor(new java.awt.Color(255, 255, 255));
        cRodadaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRodadaAtualActionPerformed(evt);
            }
        });
        getContentPane().add(cRodadaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 115, 103, 35));

        cNome.setEditable(false);
        cNome.setBackground(new java.awt.Color(51, 51, 51));
        cNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cNome.setForeground(new java.awt.Color(255, 255, 255));
        cNome.setCaretColor(new java.awt.Color(255, 255, 255));
        cNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNomeActionPerformed(evt);
            }
        });
        getContentPane().add(cNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 355, 230, 30));

        ganhei.setBackground(new java.awt.Color(0, 0, 0));
        ganhei.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        ganhei.setForeground(new java.awt.Color(0, 255, 0));
        ganhei.setText("Ganhei");
        getContentPane().add(ganhei, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 80, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Interface de Apostas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        cCalcPraColocar.setEditable(false);
        cCalcPraColocar.setBackground(new java.awt.Color(51, 51, 51));
        cCalcPraColocar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cCalcPraColocar.setForeground(new java.awt.Color(255, 255, 255));
        cCalcPraColocar.setCaretColor(new java.awt.Color(255, 255, 255));
        cCalcPraColocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCalcPraColocarActionPerformed(evt);
            }
        });
        getContentPane().add(cCalcPraColocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 155, 103, 35));

        nova1.setBackground(new java.awt.Color(0, 0, 0));
        nova1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        nova1.setForeground(new java.awt.Color(255, 255, 255));
        nova1.setText("Novo Apostador");
        nova1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nova1ActionPerformed(evt);
            }
        });
        getContentPane().add(nova1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("jLabel8");
        jLabel8.setEnabled(false);
        jLabel8.setFocusable(false);
        jLabel8.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel8.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 435, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cSaldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSaldoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSaldoTotalActionPerformed

    private void cSaldoDasRodadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSaldoDasRodadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSaldoDasRodadasActionPerformed

    private void novaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_novaActionPerformed

    private void cRodadaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRodadaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cRodadaAtualActionPerformed

    private void cNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNomeActionPerformed

    private void cCalcPraColocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCalcPraColocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCalcPraColocarActionPerformed

    private void nova1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nova1ActionPerformed
        TelaNova tela = new TelaNova(null, true);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        montaTela(tela.getCliente());
    }//GEN-LAST:event_nova1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main dialog = new Main(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cCalcPraColocar;
    private javax.swing.JTextField cNome;
    private javax.swing.JTextField cRodadaAtual;
    private javax.swing.JTextField cSaldoDasRodadas;
    private javax.swing.JTextField cSaldoTotal;
    private javax.swing.JButton ganhei;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton nova;
    private javax.swing.JButton nova1;
    private javax.swing.JButton perdi;
    // End of variables declaration//GEN-END:variables
}
